name: mxlive
description: Premium Live Streaming App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # নেটওয়ার্ক এবং ক্যাশিং
  http: ^1.2.0
  cached_network_image: ^3.3.1
  # ভিডিও প্লেয়ার (চরম প্রিমিয়াম)
  chewie: ^1.7.4
  video_player: ^2.8.3
  # ডিজাইন এবং আইকন
  google_fonts: ^6.1.0
  marquee: ^2.2.3
  url_launcher: ^6.2.5
  wakelock_plus: ^1.1.4 # স্ক্রিন অন রাখার জন্য

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
